name: Publish package to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

env:
  RELEASE_VERSION: ${{ inputs.version }}

jobs:
  publish:
    runs-on: [self-hosted, ex44]
    container: explyt/plugin-env:v2.0.0
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish to GitHub Packages
        run: >-
          mvn -X -Drevision=${{ env.RELEASE_VERSION }}
          -DaltDeploymentRepository=github::https://maven.pkg.github.com/explyt/spring-ai
          --batch-mode --settings ~/.m2/settings.xml deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
