name: Publish package to the Maven Central Repository and GitHub Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (the same as last release version)'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version (the same as last release version)'
        required: true
        type: string

env:
  RELEASE_VERSION: ${{ inputs.version }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
      - name: Publish to GitHub Packages
        run: mvn -Drevision=env.RELEASE_VERSION --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
