name: Publish package to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

env:
  RELEASE_VERSION: ${{ inputs.version }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
      - name: Publish to GitHub Packages
        run: |
          mvn -pl ':spring-ai-retry,:spring-ai-openai,:spring-ai-ollama,:spring-ai-anthropic,:spring-ai-google-gemini,:spring-ai-deepseek,:spring-ai-mistral-ai,:spring-ai-model,:spring-ai-commons,:spring-ai-template-st,:spring-ai-vertex-ai-gemini,:spring-ai-azure-openai,:spring-ai-bedrock' \
            -am \
            -Drevision=${{ env.RELEASE_VERSION }} \
            -DaltDeploymentRepository=github::https://maven.pkg.github.com/explyt/spring-ai \
            --batch-mode --settings ~/.m2/settings.xml -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
