name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build branch
    runs-on: [self-hosted, ex44]
    container: explyt/plugin-env:v2.0.0
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          ./mvnw --batch-mode test
